version: 2
mergeable:
  # see https://mergeable.readthedocs.io/en/latest/configuration.html
  - when: pull_request.*
    name: 'Changelog check'
    filter:
      - do: payload
        pull_request:
          description:
            must_exclude:
              regex: '\\s*skip changelog check\\s*'
    validate:
      - do: and
        validate:
          - do: dependent
            changed:
              file: 'packages/frontend/**'
              required: ['CHANGELOG.md']
          - do: dependent
            changed:
              file: 'packages/runtime/**'
              required: ['CHANGELOG.md']
          - do: dependent
            changed:
              file: 'packages/shared/**'
              required: ['CHANGELOG.md']
          - do: dependent
            changed:
              file: 'packages/target-browser/**'
              required: ['CHANGELOG.md']
          - do: dependent
            changed:
              file: 'packages/target-electron/**'
              required: ['CHANGELOG.md']
          - do: dependent
            changed:
              file: 'packages/target-tauri/**'
              required: ['CHANGELOG.md']
          - do: dependent
            changed:
              file: 'scss/**'
              required: ['CHANGELOG.md']
          - do: dependent
            changed:
              file: 'static/help/**'
              required: ['CHANGELOG.md']
    fail:
      - do: checks
        status: 'action_required'
        payload:
          title: Changelog needs to be updated
          summary: 'Please update the changelog'
    error: 
      - do: checks
        status: 'action_required'
        payload:
          title: error
          summary: 'Changelog check error'
