# .prettierrc
trailingComma: es5
tabWidth: 2
semi: false
singleQuote: true
jsxSingleQuote: true
endOfLine: auto
arrowParens: avoid

overrides:
- files: "*.json5"
  options:
    singleQuote: false
    quoteProps: preserve
    trailingComma: none
    parser: json5
