packages:
  - packages/*
catalog:
  # deltachat specific
  '@deltachat/jsonrpc-client': 1.159.4
  '@deltachat/stdio-rpc-server': 1.159.4
  '@webxdc/types': ^2.1.2

  # dependencies
  '@types/mime-types': ^2.1.4
  mime-types: ^2.1.35

  # tools / dev dependencies
  typescript: ^5.5.4
  typescript-plugin-css-modules: ^5.1.0

  sass: ^1.86.3
