packages:
  - packages/*
catalog:
  # deltachat specific
  '@deltachat/jsonrpc-client': 1.142.12
  '@deltachat/stdio-rpc-server': 1.142.12
  webxdc-types: ^1.0.1

  # dependencies
  '@types/mime-types': ^2.1.4
  mime-types: ^2.1.35

  # tools / dev dependencies
  typescript: ^5.5.4
  typescript-plugin-css-modules: ^5.1.0

  sass: ^1.77.8