packages:
  - packages/*

catalog:
  '@deltachat/jsonrpc-client': 2.11.0
  '@deltachat/stdio-rpc-server': 2.11.0
  '@types/mime-types': ^2.1.4
  '@webxdc/types': ^2.1.2
  mime-types: ^2.1.35
  sass: ^1.86.3
  typescript: ^5.9.2
  typescript-plugin-css-modules: ^5.2.0
