packages:
  - packages/*
catalog:
  # deltachat specific
  '@deltachat/jsonrpc-client': 2.20.0
  '@deltachat/stdio-rpc-server': 2.20.0
  '@webxdc/types': ^2.1.2
  '@deltachat/calls-webapp': "0.10.0-beta-debug"

  # dependencies
  '@types/mime-types': ^2.1.4
  mime-types: ^2.1.35

  # tools / dev dependencies
  sass: ^1.86.3
  typescript: ^5.9.2
  typescript-plugin-css-modules: ^5.2.0
  '@types/node': ^20.14.13
