import {
  ONE_HOUR_IN_SECONDS,
  TWO_HOURS_IN_SECONDS,
  ONE_DAY_IN_SECONDS,
  ONE_WEEK_IN_SECONDS,
  ZERO_SECONDS,
  FOUR_WEEKS_IN_SECONDS,
  ONE_YEAR_IN_SECONDS,
} from './constants'

export enum MuteDuration {
  OFF = ZERO_SECONDS,
  ONE_HOUR = ONE_HOUR_IN_SECONDS,
  TWO_HOURS = TWO_HOURS_IN_SECONDS,
  ONE_DAY = ONE_DAY_IN_SECONDS,
  SEVEN_DAYS = ONE_WEEK_IN_SECONDS,
  FOREVER = -1,
}

export enum AutodeleteDuration {
  OFF = ZERO_SECONDS,
  ONE_HOUR = ONE_HOUR_IN_SECONDS,
  ONE_DAY = ONE_DAY_IN_SECONDS,
  ONE_WEEK = ONE_WEEK_IN_SECONDS,
  FOUR_WEEKS = FOUR_WEEKS_IN_SECONDS,
  ONE_YEAR = ONE_YEAR_IN_SECONDS,
}
