[package]
name = "register-default-handler"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
objc2 = { version = "0.6", features = ["exception"] }
objc2-foundation = { version = "0.3.0", default-features = false, features = [
    "std",
    "objc2-core-foundation",
    "NSString",
    "NSBundle",
    "NSURL",
] }
objc2-app-kit = { version = "0.3.1", default-features = false, features = [
    "std",
    "block2",
    "NSWorkspace",
] }
