[package]
name = "translationfn"
version = "0.1.0"
edition = "2024"

[dependencies]
intl_pluralrules = "7.0.2"
log = "0.4.26"
unic-langid = "0.9.5"
thiserror = "2.0.11"
regex = "1.11.1"

[dev-dependencies]
serde_json = "1.0.140"
