name: Code Checks for rust part of delta tauri

on:
  pull_request:
    paths:
      - packages/target-tauri/**

permissions: {}

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          show-progress: false
          persist-credentials: false
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: 1.88
          components: rustfmt
      - run: cargo fmt --all -- --check

  run_clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          show-progress: false
          persist-credentials: false
      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
        with:
          toolchain: 1.88
          components: clippy
          cache: false
      - name: fake html dist dir to make it build
        run: |
          mkdir packages/target-tauri/html-dist
          touch packages/target-tauri/html-dist/tauri_main.html
      - name: Run clippy
        env:
          VERSION_INFO_GIT_REF: ${{ github.ref }}
        run: cargo clippy --workspace --tests --examples

  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          show-progress: false
          persist-credentials: false
      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: 1.88
      - name: fake html dist dir to make it build
        run: |
          mkdir packages/target-tauri/html-dist
          touch packages/target-tauri/html-dist/tauri_main.html
      - name: Unit tests
        env:
            VERSION_INFO_GIT_REF: "testing"
        run: cargo test --all
